language: node_js

node_js:
  - "node"
  - "10"

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
  - os: windows

env:
  global:
    - PACKAGE_VERSION=$(node -p -e "require('$HOME/package.json').version")
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

cache: npm

script:
  - npm run dist

before_deploy:
  - echo $PACKAGE_VERSION

deploy:
  overwrite: true
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - $HOME/dist/MTG-Arena-Tool $PACKAGE_VERSION.AppImage
    - $HOME/dist/MTG-Arena-Tool $PACKAGE_VERSION.dmg
    - $HOME/dist/MTG-Arena-Tool $PACKAGE_VERSION.exe
  skip_cleanup: true
  draft: false
  on:
    repo: Manuel-777/mtg-arena-tool-travis-test
    tags: true
