language: node_js

node_js:
  - "10"

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
  - os: windows

env:
  global:
    - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

cache: npm

script:
  - npm run dist

deploy:
  overwrite: true
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $PACKAGE_VERSION
  skip_cleanup: true
  draft: true
