language: node_js

node_js:
  - "10"

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

cache: npm

script:
  - npm run dist

deploy:
  overwrite: true
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "$HOME/dist/MTG-Arena-Tool-*-x86_64.AppImage"
    - "$HOME/dist/MTG-Arena-Tool-*.pkg"
  skip_cleanup: true
  draft: true
  on:
    repo: Manuel-777/mtg-arena-tool-travis-test
    tags: true
